### ISSUE TITLE
Build fails with React-Native

### ISSUE THREAD

**Issue by jihopark** [realtime-framework/RCTRealtimeMessagingAndroid#1]
I did all the procedures on https://github.com/realtime-framework/RCTRealtimeMessagingAndroid

but I get this error.

```
/Users/parkjiho/Documents/react-native-projects/plainX/android/app/src/main/java/com/plainx/MainActivity.java:29: error: cannot find symbol
                .addPackage(new CustomReactPackage())
                                ^
  symbol:   class CustomReactPackage
  location: class MainActivity
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I think I am doing something wrong for
- Drag all files node_modules/react-native-realtimemessaging-android to your src package folder

Does this suppose to mean to have a folder `react-native-realtimemessaging-android` or contents of this folder inside `/project-root/android/app/src`  ?

Neither fails to build. With the error above.

**Comment by JoaoCaixinha** [comment]
hi, yes you drag to /project-root/android/app/src and switch the classes import package. let me know if this helps.
