### ISSUE TITLE
Unable to find RealtimeDroid

### ISSUE THREAD

**Issue by NoxidNawk** [realtime-framework/RCTRealtimeMessagingAndroid#10]
I have imported the unity package and try build on an android device, and it shows the following error
Unable to find RealtimeDroid
Unable to find RealtimeDroid
Unable to find RealtimeDroid
Unable to find RealtimeDroid
Unable to find RealtimeDroid
Unable to find RealtimeDroid
Realtime.Ortc.Api.OrtcException: Connection Failed. An exception was thrown by the type initializer for Realtime.Ortc.Internal.DroidConnection

**Comment by JoaoCaixinha** [comment]
Hi, can you provide more details? How did you import the SDK? how are you connecting?

**Comment by NoxidNawk** [comment]
Hi Joao, just fixed it by moving correct .so file to Plugins folder, Thanks
