### ISSUE TITLE
Inappropriate naming CustomReactPackage

### ISSUE THREAD

**Issue by awesomejerry** [realtime-framework/RCTRealtimeMessagingAndroid#12]
CustomReactPackage is so ambiguous. It should be named as RNRealtimeMessaging or whatsoever that represents what it is as a module that provids realtime-messaging.

**Comment by realtime-framework** [comment]
We agree and will update in an upcoming release.

**Comment by realtime-framework** [comment]
Fixed by https://github.com/realtime-framework/RCTRealtimeMessagingAndroid/blob/1.1.0/reactnativemessagingandroid/src/main/java/co/realtime/reactnativemessagingandroid/RealtimeMessagingPackage.java#L16
