### ISSUE TITLE
unable to extend two packages at the same time

### ISSUE THREAD

**Issue by kriuvi** [realtime-framework/RCTRealtimeMessagingAndroid#13]
I want to use RCTRealtimeMessagingAndroid for push notifications. 
1) In the documentation is stated that: 
'If you want to use push notifications, set MainActivity extending RealtimePushNotificationActivity"

But MainActivity already extends ReactActivity. How to be in this situation? 

2) Drag RCTRealtimeMessagingAndroid.js to the root of your project.
it means root directory or android/app/src as was suggested in one of the closed issues?

**Comment by JoaoCaixinha** [comment]
Hi vikri, 
check the new [version 1.0.6](https://www.npmjs.com/package/react-native-realtimemessaging-android)
Now RealtimePushNotificationActivity extends ReactActivity, and you should drag 
`RCTRealtimeMessagingAndroid.js` to the same place as `index.android.js` file.
Best regards.

**Comment by ghost** [comment]
I think this readme needs some clarifications.
- in which file should the following be edited: Add new RealtimeMessagingPackage() to the getPackages() method return list in MainActivity. ?
- in which file should the following be edited: "If you want to use push notifications, set MainActivity extending RealtimePushNotificationActivity." ?

**Comment by JoaoCaixinha** [comment]
Hi herve1976, you should perform that changes in MainActivity.java file.

```
    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
                new RealtimeMessagingPackage()
        );
    }

```

and 

`public class MainActivity extends RealtimePushNotificationActivity`

Hope this answer your question, let me know if it does.

**Comment by ghost** [comment]
Please confirm that MainActivity.java initially does not have the getPackages method definition, so I need to add it as you wrote.

Also I did the all changes as you said but I have the following error:

```
...
:react-native-realtime-messaging-android:compileReleaseJavaWithJavac
/Users/herve76/Desktop/AndRealtimeRCT/node_modules/react-native-realtimemessaging-android/reactnativemessagingandroid/src/main/java/co/realtime/reactnativemessagingandroid/RealtimePushNotificationActivity.java:32: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-realtime-messaging-android:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

**Comment by JoaoCaixinha** [comment]
Hi herve1976, witch version of react-native are you using?

**Comment by ghost** [comment]
react-native-cli: 1.0.0
react-native: 0.31.0

**Comment by ghost** [comment]
Here is the content of my MainActivity.java

```
package com.andrealtimerct;

import com.facebook.react.ReactActivity;
import co.realtime.reactnativemessagingandroid.RealtimeMessagingPackage;

public class MainActivity extends RealtimePushNotificationActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "AndRealtimeRCT";
    }

    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
                new RealtimeMessagingPackage()
        );
    }

}

```

**Comment by realtime-framework** [comment]
Hi @herve1976, the solution is here: https://github.com/realtime-framework/RCTRealtimeMessagingAndroid/commit/2ca3802e145a6c02a4d956d9272363636d309a43#diff-04c6e90faac2675aa89e2176d2eec7d8R34
