### ISSUE TITLE
the app received messages but not the notifications

### ISSUE THREAD

**Issue by bitcoinvsalts** [realtime-framework/RCTRealtimeMessagingAndroid#20]
I followed the README instructions and it seems like it's connecting, subscribing and sending.

even sending a message from the console I even get the log: Received message etc...

But if I put the app in the background and send a message from the console, I do not get the notifcation but I still get the "Received message..." log. Any idea why?

**Comment by realtime-framework** [comment]
Please check if you are using the correct Firebase Sender Id.
