### ISSUE TITLE
Readme installation has wrong directory

### ISSUE THREAD

**Issue by jihopark** [realtime-framework/RCTRealtimeMessagingAndroid#6]
On `settings.gradle`, the projectDir should be 

```
new File(settingsDir,'../node_modules/react-native-realtimemessaging-android/reactnativemessagingandroid')
```

Because build.gradle is located there. Or else gradle won't build.

**Comment by Kuzmin** [comment]
The package published on NPM still has the faulty README :)

**Comment by jparreira** [comment]
Thanks @Kuzmin, it's fixed now.
