### ISSUE TITLE
undefined is not an object GcmModule.launchNotification"

### ISSUE THREAD

**Issue by sssahas** [realtime-framework/RCTRealtimeMessagingAndroid#9]
Followed the instructions here. 
Had to make this one little change to get it compiling in the MainActivity.java
import co.realtime.reactnativemessagingandroid.RealtimePushNotificationActivity;

Then I was able to deploy the app to an emulator and getting this error on launch.. 
Searching 12341 files for "12-25 18:29:24.797  2380  2411 E ReactNativeJS: undefined is not an object (evaluating 'GcmModule.launchNotification')
GcmModule.launchNotification"

Does this work on emulators? I don't get this error on real device but can't depend on just real device for development. Any thoughts?

**Comment by tcruzibt** [comment]
Hi,

Do you have Google APIs on your emulator?

Thanks

**Comment by jparreira** [comment]
@sahas- any news on this issue?

**Comment by sssahas** [comment]
Thanks for the reminder.
I did reinstall my google play services on the emulator and seeing this error.
"ReactNativeJS: undefined is not an object (evaluating 'ortcClient.checkForNotifications')" - RTRealtimeMessagingAndroid.js - 120..

Looks like my emulator is missing something, I got some work to do..

Thanks !

**Comment by tcruzibt** [comment]
The file should be RCTRealtimeMessagingAndroid.js

**Comment by sssahas** [comment]
Sorry, I might have had a typo, attached a screenshot, welcome any suggestions.

![screenshot 8](https://cloud.githubusercontent.com/assets/10361685/12105196/2ab36398-b318-11e5-8cde-bcb0619f97a9.png)

**Comment by tcruzibt** [comment]
It seems that the ortcClient is not being initialized. Have you imported the react-native-realtimemessaging-android project to Android Studio like explained [here](https://github.com/realtime-framework/RCTRealtimeMessagingAndroid/blob/master/README.md)?

**Comment by sssahas** [comment]
yes, the same code works on real device and on 5.x lollipop but fails in marshmallow. I'll try a different marshmallow emulator tonight and update.

**Comment by jparreira** [comment]
Closing for now. Please reopen if needed.
